"""empty message

Revision ID: 33d55d380739
Revises: 
Create Date: 2024-01-29 13:25:36.601152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d55d380739'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(length=50), nullable=False),
    sa.Column('away_team', sa.String(length=50), nullable=False),
    sa.Column('winner', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['away_team'], ['team.name'], ),
    sa.ForeignKeyConstraint(['home_team'], ['team.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixture')
    op.drop_table('team')
    # ### end Alembic commands ###
